version: '3'

services:
 xserver:
  image: hlacontainers/xserver
  ports:
  - "8080:8080"
 
 crc:
  image: ${REPOSITORY}pitch-crc:${PITCH_VERSION}
  mac_address: ${MAC_ADDRESS}
  environment:
  - DISPLAY=xserver:0
  ports:
  - "8989:8989"
